### ISSUE TITLE
CCTAATGGTCCAGAC ignored along with GGGGGGGGGGGGGG?

### ISSUE THREAD

**Issue by xmao** [NKI-GCF/featureseek#1]
Wondering what CCTAATGGTCCAGAC is?

**Comment by veldsla** [comment]
We sometimes see these sequences in relatively high numbers. The GGGG thing could be sequencing related. If you google the other sequence you find a hit in a document about feature barcode antibody conjugation kit. I think it is some kind of by-product or contamination.

You can check the number of ignored reads in the report. If you have a high number you can count them by running `featureseek` with `-x "" -u`

This program needs some more work. Better filtering options and really some sort of valid barcode detection would be nice. Let me know if you think it is useful

**Comment by veldsla** [comment]
The issue has been picked up by 10X Genomics support they asked me to post the following message:
> 10x Genomics has requested that anyone who has seen high levels of this sequence in their data should contact technical support at: [support@10xgenomics.com](mailto:support@10xgenomics.com) so they can review the data with you."
